### PR TITLE
Agreed changes from London

### LINKED ISSUE #10: You never go full TAPS
The charter currently states:
> Define a conceptual framework for describing abstract algorithms that can have concrete instantiations for each transport, and an approach to documenting each.

This sounds like quite a distraction from the useful work of new congestion control algorithms. In the real world, we have TCP and QUIC - we don't need an ontology here of all hypothetical options that will then only ever be instantiated exactly twice for QUIC and TCP.

### PR DESCRIPTION
**Pull request by martinduke**
Fixes #10, #14, #15, #17

### CODE REVIEW

**Comment by nealcardwell** [comment]
Looks good to me. Thanks, Martin!

**Comment by bbriscoe** [comment]
Looking good. The last phrase here leapt out at me:
> AQM algorithms, in consultation with TSVWG, based on the available time in
> both groups and the extent that the algorithm requires changes to congestion
> control. 

Suggested it's just deleted:
> AQM algorithms, in consultation with TSVWG, based on the available time in
> both groups. 

Rationale: In general we cannot deploy AQMs that require changes to CCAs, just as we cannot deploy CCAs that require changes to AQMs. 

It's possible that sthg like the following was intended:
> ... and the extent to which the algorithm needs to support a wide 
> range of congestion controls

But I'm not sure there will be any examples of an AQM that only needs to support a narrow range of CCAs, hence the initial suggestion to just delete the final phrase.

**Review by mwelzl — COMMENTED** [review]
LGTM
(I didn't click "approve" because it feels weird for me to do that  :-)   )

**Comment by mohittahiliani** [comment]
Looks good to me!

**Comment by martinduke** [comment]
Hi Bob,

Perhaps you've heard of draft-ietf-tsvwg-aqm-dualq-coupled, which I would classify as an AQM document, and is very much meant to interact with a specific class of congestion controls (that meet the Prague requirements?) ;-)

I clearly didn't capture it in text correctly, but are there AQM documents intimately tied to congestion control and others that are not? Can you give me an example or two of what kind of work you would like this WG to take up?

**Comment by bbriscoe** [comment]
@martinduke,
> Perhaps you've heard of draft-ietf-tsvwg-aqm-dualq-coupled, which I would classify as an AQM document, and is very much meant to interact with a specific class of congestion controls (that meet the Prague requirements?) ;-)

I actually thought of that when I wrote my response. I said "In general we cannot deploy AQMs that require changes to CCAs," because I read "the extent to which an algorithm requires changes to congestion control" as "...requires changes to already deployed congestion control algorithms." 

But perhaps you meant "...changes to customary congestion control practice," which would describe the DualQ. If so, it's still not clear which way such AQMs would be sent - tsvwg or congress? And it's not clear (to me) why this would be a factor in decided which WG handled an AQM.

> I clearly didn't capture it in text correctly, but are there AQM documents intimately tied to congestion control and others that are not? 

PIE, PI2, CoDel are all optimized for Reno-Friendly CCAs. PIE and PI2 manage to bring more aggressive CCAs (and even unresponsive flows) under control nearly as quickly as Reno (within 200-300ms). However, CoDel is very specific to Reno, and effectively collapses in the face of a more aggressive CCA (or just multiple Reno flows). As shown in [Fig 5 here](https://github.com/L4STeam/l4steam.github.io/tree/master/overload-results), CoDel takes about 100s to increase drop sufficiently to bring an unresponsive flow under control.

> Can you give me an example or two of what kind of work you would like this WG to take up?

Personally, I would like to have some time out in the field with the experimental track stuff we've done recently (DualPI2). But give it a couple of years and we might be bringing an updated variant of that for stds. We've also seen some interest (offlist) in an AQM that approximates the outcome of a DualQ for core nodes with large numbers of flows. The idea would be a pair of very simple AQMs within a single queue. I guess that would be experimental track initially. 

I'd also like to see the L4S variant of FQ_CoDel developed further, tested and written up. Actually it's really the L4S variant of FQ_*, because an L4S flow doesn't exercise the CoDel algo at all.

If CoDel itself were brought to the group for stds track, the control law would need to be fixed (see above link for how unresponsive traffic kills it).

**Comment by chromi** [comment]
> On 16 Nov, 2022, at 1:00 am, Bob Briscoe ***@***.***> wrote:
> 
> If CoDel itself were brought to the group for stds track, the control law would need to be fixed (see above link for how unresponsive traffic kills it).

I could certainly bring something to the WG along those lines.  Some of you might remember me talking about COBALT, which is essentially a combination of Codel and BLUE in tandem, specifically to address this particular problem.  An ambiguity in RFC-8289, which its reference implementation handles poorly, is also dealt with.  One version of COBALT is already quite widely deployed on the Internet, and the feedback I'm getting is positive.

Similarly, I could bring in a more sophisticated FQ scheme than is described in RFC-8290, which is similarly deployed and receiving positive feedback (in the same qdisc module as COBALT).

If we can at least agree that this kind of thing would be in-scope, then we might be getting somewhere.

 - Jonathan Morton

**Comment by martinduke** [comment]
Alright Bob, I deleted the offending phrase and replaced it with "available review expertise." Submitting.

**Pull request merged**
